# Python Additional Warmup Task

In this session we will go through the commonly used python and numpy functions in machine learning or data analystics related tasks.

## Task 1: Import numpy as np and see the version

Hint: use *import*  and "\__version\__" from numpy

In [0]:
## Write your code here ##

## Task 2: How to create a 1D array?

Expected Output: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
## Write your code here ##

## Task 3: Create arrays in different way

### Task 3.1: How to create a 4x4 boolean numpy array?

Hint: np.full()

Expected Output:
array( [[ True,  True,  True,  True],
       [ True,  True,  True,  True], 
       [ True,  True,  True,  True], 
       [ True,  True,  True,  True]])

In [0]:
## Write your code here ##

### Task 3.2: How to create an array and initial all the values to zero?

Hint: np.zeros()

In [0]:
## Write your code here ##

### Task 3.3: How to extract items that satisfy a given condition from 1D array?

Questions: Extract all odd numbers from an array

Input: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Expected Output: [1,3,5,7,9]

In [0]:
## Write your code here ##
# Input
arr = 

# Solution


## Task 4: How to reshape an array?

Question: Convert a 1D array to a 2D array with 2 rows

Input: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Expected Output:
array([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]])

In [0]:
## Write your code here ## 

## Task 5: How to get the common items between two python numpy arrays?

Questions: Get the common items between array a and b

**Input** : 

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

**Expected Output: **

[2, 4]


**Hint: **use np.intersect1d()

In [0]:
## Write your code here ##

## Task 6: How to create a 2D array containing random floats between 5 and 10?

Questions: Create a 2D array of shape 5x3 to contain random decimal numbers between 4 and 10.

**Hint:** use np.random.uniform()

In [0]:
## Write your code here ##

## Task 7: How to normalize an array so the values range between 0 and 1?

**Input**: 

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

**Hint:** use np.max() and np.min()--> to find the maximun and minimun value in an array



In [0]:
## Write your code here ##

## Task 8:  How to find if a given array has any null values?

** Input **

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


**Hint:** use np.isnan()


In [0]:
# Input
## Write your code here ##

## Task 9: How to replace all values greater than a given value to a given cutoff?

Question: 

From the array a, replace all values greater than 100 to 1 and less than 100 to 0.

**Hint**: np.where() [Reference](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html)

**Input**:

array = np.array([100, 120, 50, 30, 200, 99, 30, 150])

**Expected Output:**
[0 1 0 0 1 0 0 1]

In [0]:
## Write your code here ##

## Task 10: How to convert an array of arrays into a flat 1d array?

**Input:**
arr1 = np.arange(3)

arr2 = np.arange(3,7)

arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])


**Expected Output:**

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


**Hint:** use np.concatenate()

In [0]:
# Input:
## Write your code here ##
      
 

## Task 11: How to generate one-hot encodings for an array in numpy?

**Input**

np.random.seed(101) 

arr = np.random.randint(1,4, size=6)

arr

array([2, 3, 2, 2, 2, 1])

**Expected Output:**

       [[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  1.,  0.],
        [ 1.,  0.,  0.]]
        
 
 **Hint:** use np.unique() and enumerate() [enumerate reference](http://book.pythontips.com/en/latest/enumerate.html)

In [0]:
# Input:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])

# Solution:
def one_hot_encodings(arr):
    ## Write your code here ##

one_hot_encodings(arr)
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])



## Task 12: Find the sum and average of an array

**Input** 

array = np.array([0,1,2,3,4,5,6,7,8,9])

**Hint: **use np.sum(), np.average()

In [0]:
## Write your code here ##

## Task 13: Find the min and max value in an array

**Input** 

array = np.array([0,1,2,3,4,5,6,7,8,9])

**Hint:** use np.min(), np.max()

In [0]:
## Write your code here ##

## Task 14: How to convert a multi dimensional array to a 1D array

**Input** 

array = np.arange(100).reshape(4, 25)

**Hint:** np.reshape()

In [0]:
## Write your code here ##


## Task 15: How to compute the mean, median, standard deviation of a numpy array?

**Input**

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris = np.genfromtxt(url, delimiter=',', dtype='object')

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])


**Hint:** use np.mean(), np.median(), np.std()

In [0]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
## Write your code here ##

## Task 16: Array indexing and slicing

NumPy array indexing is a rich topic, as there are many ways you may want to select a subset of your data or individual elements

### Task 16.1: Creating subsets from a 1D array:

Question: Given an array for 10 integers, extract all the elements from 5th to 8th.

**Input:**
array = np.array([12, 23, 54, 23, 67, 90, 100, 23, 56, 82])

**Hint:**
array[start:end]

Note: Array index starts from 0

In [0]:
## Write your code here ##

### Task 16.2 Creating subsets from a 2D array:

Question:Given a 2D array, 

**Input**: np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

**Expected Output:**

[[5 6]
 [8 9]]
 
 
 **Hint:** array[rowstart:rowend, colstart:colend]

In [0]:
## Write your code here ##